name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  syncfusion_flutter_charts: ^23.1.38
  google_fonts: ^4.0.4
  image_picker: ^1.0.7
  mobile_scanner: ^3.5.2
  intl: ^0.18.0
  fl_chart: ^0.66.0
  shared_preferences: ^2.2.2
  multi_select_flutter: 4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo_SMH.png"


flutter:
  uses-material-design: true

